package com.wpaul15.scryfall.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.URI;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;
import lombok.Builder;

@Builder
public record Card(
    // Core Fields
    @JsonProperty("arena_id") int arenaId,
    UUID id,
    Language lang,
    @JsonProperty("mtgo_id") int mtgoId,
    @JsonProperty("mtgo_foil_id") int mtgoFoilId,
    @JsonProperty("multiverse_ids") List<Integer> multiverseIds,
    @JsonProperty("tcgplayer_id") int tcgplayerId,
    @JsonProperty("tcgplayer_etched_id") int tcgplayerEtchedId,
    @JsonProperty("cardmarket_id") int cardmarketId,
    String object,
    @JsonProperty("oracle_id") UUID oracleId,
    @JsonProperty("prints_search_uri") URI printsSearchUri,
    @JsonProperty("rulings_uri") URI rulingsUri,
    @JsonProperty("scryfall_uri") URI scryfallUri,
    URI uri,
    // Gameplay Fields,
    @JsonProperty("all_parts") List<RelatedCard> allParts,
    @JsonProperty("card_faces") List<CardFace> cardFaces,
    double cmc,
    @JsonProperty("color_identity") List<Colors> colorIdentity,
    @JsonProperty("color_indicator") List<Colors> colorIndicator,
    List<Colors> colors,
    @JsonProperty("edhrec_rank") int edhrecRank,
    @JsonProperty("hand_modifier") String handModifier,
    List<String> keywords,
    Layout layout,
    Legalities legalities,
    @JsonProperty("life_modifier") String lifeModifier,
    String loyalty,
    @JsonProperty("mana_cost") String manaCost,
    String name,
    @JsonProperty("oracle_text") String oracleText,
    boolean oversized,
    String power,
    @JsonProperty("produced_mana") List<Colors> producedMana,
    boolean reserved,
    String toughness,
    @JsonProperty("type_line") String typeLine,
    // Print Fields
    String artist,
    @JsonProperty("artist_ids") List<UUID> artistIds,
    boolean booster,
    @JsonProperty("border_color") String borderColor,
    @JsonProperty("card_back_id") UUID cardBackId,
    @JsonProperty("collector_number") String collectorNumber,
    @JsonProperty("content_warning") boolean contentWarning,
    boolean digital,
    List<Finish> finishes,
    @JsonProperty("flavor_name") String flavorName,
    @JsonProperty("flavor_text") String flavorText,
    boolean foil,
    @JsonProperty("frame_effects") List<FrameEffect> frameEffects,
    Frame frame,
    @JsonProperty("full_art") boolean fullArt,
    List<Game> games,
    @JsonProperty("highres_image") boolean highResImage,
    @JsonProperty("illustration_id") UUID illustrationId,
    @JsonProperty("image_status") ImageStatus imageStatus,
    @JsonProperty("image_uris") ImageUris imageUris,
    boolean nonfoil,
    Prices prices,
    @JsonProperty("printed_name") String printedName,
    @JsonProperty("printed_text") String printedText,
    String printTypeLine,
    boolean promo,
    @JsonProperty("promo_types") List<String> promoTypes,
    @JsonProperty("purchase_uris") PurchaseUris purchaseUris,
    Rarity rarity,
    @JsonProperty("related_uris") RelatedUris relatedUris,
    @JsonProperty("released_at") LocalDate releasedAt,
    boolean reprint,
    @JsonProperty("scryfall_set_uri") URI scryfallSetUri,
    @JsonProperty("set_name") String setName,
    @JsonProperty("set_search_uri") URI setSearchUri,
    @JsonProperty("set_type") String setType,
    @JsonProperty("set_uri") URI setUri,
    String set,
    @JsonProperty("set_id") String setId,
    @JsonProperty("story_spotlight") boolean storySpotlight,
    boolean textless,
    boolean variation,
    @JsonProperty("variation_of") UUID variationOf,
    @JsonProperty("security_stamp") SecurityStamp securityStamp,
    String watermark,
    Preview preview) {}
